### ISSUE TITLE
A strongly-named assembly is required

### ISSUE THREAD

**Issue by abaka-spn** [jamesharling/Microsoft.Owin.Security.ApiKey#10]
Hi, 
 
I added your package by nuget in my project and when I start it I have the exception below

`Could not load file or assembly 'Microsoft.Owin.Security.ApiKey, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044). `

Is it possible to sign the assembly ? or How work around this error ?

**Comment by jamesharling** [comment]
If it's possible to turn off your project's requirement of strongly-named assemblies then you should have no problems after that. If not, let me know and I can investigate the feasbility of strongly naming this library/assembly.

**Comment by abaka-spn** [comment]
Sorry, I'm not expert and I don't known how to turn off the strongly-named .
I tried to apply this doc [how-to-disable-the-strong-name-bypass-feature](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-disable-the-strong-name-bypass-feature) but it doesn't work, perhaps, I need to add code in my app. 

The workaround (for this moment) is to import your project into my solution as a new project and sign it.

Is it secure to turn off strongly-named ?

Is it possible to you to sign your assembly ? I would be happy
