### ISSUE TITLE
.NET Core support?

### ISSUE THREAD

**Issue by jeroenwo** [jamesharling/Microsoft.Owin.Security.ApiKey#11]
Currently this awesome project only supports .NET.
Can we please have the .NET Core flavor as well? :)

**Comment by jamesharling** [comment]
This will likely have to be a totally separate project for .NET Core but I don't see why not! Watch this space, I'll post updates here so you can find it.

**Comment by jamesharling** [comment]
Please take a look at [Microsoft.AspNetCore.Authentication.ApiKey](https://github.com/jamesharling/Microsoft.AspNetCore.Authentication.ApiKey) for .NET Core support. Enjoy!
